# Generated by Django 5.1.3 on 2025-05-25 13:36

import django.db.models.deletion
import mainapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(default=mainapp.models.get_today)),
                ('end_date', models.DateTimeField(default=mainapp.models.get_today)),
                ('category', models.CharField(choices=[('important', 'Important'), ('private', 'Private'), ('club', 'Science Club'), ('student_council', 'Student Council'), ('tul_events', 'TUL Events')], max_length=20)),
                ('color', models.CharField(blank=True, max_length=10)),
                ('repeat_type', models.CharField(choices=[('none', 'None'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='Anonymous User', max_length=63)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('was_edited', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('replying_to', models.ManyToManyField(blank=True, related_name='replies', to='mainapp.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='thread_details', serialize=False, to='mainapp.post')),
                ('category', models.CharField(max_length=63)),
                ('title', models.CharField(max_length=1023)),
                ('visible_for_teachers', models.BooleanField(default=False)),
                ('can_be_answered', models.BooleanField(default=True)),
                ('last_activity_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('thread_nickname', models.CharField(blank=True, max_length=63, null=True)),
                ('thread_is_anonymous', models.BooleanField(blank=True, null=True)),
                ('thread_date', models.DateTimeField(blank=True, null=True)),
                ('thread_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='mainapp.thread'),
        ),
    ]
