# Generated by Django 5.2 on 2025-04-26 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=63)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('was_edited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.post')),
                ('category', models.CharField(max_length=63)),
                ('title', models.CharField(max_length=1023)),
                ('visible_for_teachers', models.BooleanField(default=False)),
                ('can_be_answered', models.BooleanField(default=True)),
                ('last_activity_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='mainapp.post')),
                ('replies_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replied_by', to='mainapp.post')),
            ],
        ),
    ]
