# Generated by Django 5.1.3 on 2025-06-16 22:58

import django.db.models.deletion
import django.utils.timezone
import mainapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default=mainapp.models.get_default_end_date)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default='000000', help_text='Unikalny kod dostępu do planu', max_length=6, null=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_created', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='subscribed_plans', through='mainapp.AppliedPlan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('category', models.CharField(choices=[('important', 'Important'), ('private', 'Private'), ('exam', 'Exam'), ('club', 'Science Club'), ('student_council', 'Student Council'), ('tul_events', 'University Events'), ('timetable_lecture', 'Timetable Lecture'), ('timetable_laboratory', 'Timetable Laboratory'), ('timetable_tutorials', 'Timetable Tutorials')], default='private', max_length=20)),
                ('color', models.CharField(editable=False, max_length=7)),
                ('repeat_type', models.CharField(choices=[('none', 'None'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=30)),
                ('room', models.CharField(max_length=50, null=True)),
                ('teacher', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('schedule_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.scheduleplan')),
            ],
        ),
        migrations.AddField(
            model_name='appliedplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='mainapp.scheduleplan'),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1023)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=63)),
                ('nickname', models.CharField(default='Anonymous User', max_length=63)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('visible_for_teachers', models.BooleanField(default=False)),
                ('can_be_answered', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_activity_date', models.DateTimeField(auto_now=True)),
                ('vote_count_cache', models.IntegerField(db_index=True, default=0)),
                ('post_count', models.IntegerField(db_index=True, default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='Anonymous User', max_length=63)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('was_edited', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('vote_count_cache', models.IntegerField(db_index=True, default=0)),
                ('replying_to', models.ManyToManyField(blank=True, related_name='replies', to='mainapp.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='mainapp.thread')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='appliedplan',
            unique_together={('user', 'plan')},
        ),
        migrations.CreateModel(
            name='PinnedThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_threads', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by_users', to='mainapp.thread')),
            ],
            options={
                'ordering': ['-pinned_at'],
                'unique_together': {('user', 'thread')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='mainapp.post')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='mainapp.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'thread'), name='unique_thread_vote_per_user'), models.UniqueConstraint(fields=('user', 'post'), name='unique_post_vote_per_user')],
            },
        ),
    ]
