# Generated by Django 5.2 on 2025-05-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleplan',
            name='is_public',
        ),
        migrations.AddField(
            model_name='scheduleplan',
            name='code',
            field=models.CharField(default='581C04', help_text='Unikalny kod dostępu do planu', max_length=6, unique=False),
        ),
    ]
