# Generated by Django 5.1.3 on 2025-06-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleplan',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
