# Generated by Django 5.2 on 2025-05-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('important', 'Important'), ('private', 'Private'), ('exam', 'Exam'), ('club', 'Scientific Club'), ('student_council', 'Student Council'), ('university', 'University-wide')], default='private', max_length=20)),
                ('color', models.CharField(choices=[('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#0000FF', 'Blue'), ('#FFFF00', 'Yellow')], default='#0000FF', max_length=7)),
                ('is_recurring', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Wydarzenie',
        ),
    ]
