# Generated by Django 5.1.3
# Placeholder migration to match database state

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        # Empty migration - original operations lost
    ]