# Generated by Django 5.1.3 on 2025-06-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_template',
        ),
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='teacher',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('important', 'Important'), ('private', 'Private'), ('exam', 'Exam'), ('club', 'Science Club'), ('student_council', 'Student Council'), ('tul_events', 'University Events'), ('timetable', 'Timetable')], default='private', max_length=20),
        ),
    ]
