# Generated by Django 5.2 on 2025-05-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_scheduleplan_is_public_scheduleplan_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleplan',
            name='code',
            field=models.CharField(blank=True, default='000000', help_text='Unikalny kod dostępu do planu', max_length=6, null=True),
        ),
    ]
