# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_event_delete_wydarzenie'),
    ]

    operations = [
        # Placeholder migration - operations already applied to database
    ]