# Generated by Django 5.1.3 on 2025-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_event_is_template_event_room_event_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('important', 'Important'), ('private', 'Private'), ('exam', 'Exam'), ('club', 'Science Club'), ('student_council', 'Student Council'), ('tul_events', 'University Events'), ('timetable_lecture', 'Timetable Lecture'), ('timetable_laboratory', 'Timetable Laboratory'), ('timetable_tutorials', 'Timetable Tutorials')], default='private', max_length=20),
        ),
    ]
