# Generated by Django 5.2 on 2025-05-06 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_event_delete_wydarzenie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_recurring',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.time(1, 0)),
        ),
        migrations.AddField(
            model_name='event',
            name='repeat_type',
            field=models.CharField(choices=[('none', 'None'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('important', 'Important'), ('private', 'Private'), ('exam', 'Exam'), ('club', 'Scientific Club'), ('university', 'University-events')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('important', '#FF0000'), ('private', '#00FF00'), ('exam', '#0000FF'), ('club', '#FFFF00'), ('university', '#FFA500')], max_length=10),
        ),
    ]
