# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_post_parent_post_post_thread_alter_thread_post_and_more'),
    ]

    operations = [
        # Placeholder migration - operations already applied to database
    ]