# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_event_is_recurring_event_end_time_and_more'),
    ]

    operations = [
        # Placeholder migration - operations already applied to database
    ]