# Generated by Django 5.2 on 2025-05-06 13:46

import datetime
import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_event_is_recurring_event_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=mainapp.models.get_today),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=mainapp.models.get_today),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
