# Generated by Django 5.2 on 2025-06-10 21:08

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_event_room_event_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedplan',
            name='end_date',
            field=models.DateField(default=mainapp.models.get_default_end_date),
        ),
    ]
