# Generated by Django 5.1.3 on 2025-06-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_event_repeat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeat_type',
            field=models.CharField(choices=[('none', 'None'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=30),
        ),
    ]
