# Generated by Django 5.2 on 2025-05-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_event_date_remove_event_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('important', 'Important'), ('private', 'Private'), ('exam', 'Exam'), ('club', 'Science Club'), ('university', 'University-events')], max_length=20),
        ),
    ]
