# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_event_date_remove_event_location_and_more'),
    ]

    operations = [
        # Placeholder migration - operations already applied to database
    ]