# Generated by Django 5.1.3 on 2025-05-06 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_remove_post_parent_post_post_replying_to"),
        ("mainapp", "0005_alter_event_category"),
    ]

    operations = []
