# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_event_category'),
        ('mainapp', '0003_remove_post_parent_post_post_replying_to'),
    ]

    operations = [
        # Merge migration - no operations needed
    ]