# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_event_category'),
    ]

    operations = [
        # Placeholder migration - operations already applied to database
    ]