# Generated by Django 5.2 on 2025-06-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_appliedplan_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_template',
        ),
        migrations.DeleteModel(
            name='ScheduleEvent',
        ),
    ]
