# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_merge_20250507_0049'),
        ('mainapp', '0006_remove_event_end_time_remove_event_start_time_and_more'),
    ]

    operations = [
        # Merge migration - no operations needed
    ]