# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_merge_20250507_0049'),
    ]

    operations = [
        # Placeholder migration - operations already applied to database
    ]