# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_post_is_anonymous_post_user'),
    ]

    operations = [
        # Placeholder migration - operations already applied to database
    ]