# Generated by Django 5.2 on 2025-05-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_merge_20250508_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('important', 'Important'), ('private', 'Private'), ('club', 'Science Club'), ('student_council', 'Student Council'), ('tul_events', 'TUL Events')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
