# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_merge_20250508_2023'),
    ]

    operations = [
        # Placeholder migration - operations already applied to database
    ]