# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_thread_content_thread_thread_author_and_more'),
    ]

    operations = [
        # Placeholder migration - operations already applied to database
    ]