# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_populate_thread_content'),
    ]

    operations = [
        # Placeholder migration - operations already applied to database
    ]