# Generated by Django 5.1.3 on 2025-05-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_populate_thread_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nickname',
            field=models.CharField(default='Anonymous User', max_length=63),
        ),
    ]
