# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_post_nickname'),
    ]

    operations = [
        # Placeholder migration - operations already applied to database
    ]