# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_event_category_alter_event_color'),
        ('mainapp', '0011_create_new_thread_table'),
    ]

    operations = [
        # Merge migration - no operations needed
    ]