# Generated by Django 5.1.3 on 2025-05-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_event_category_alter_event_color'),
        ('mainapp', '0010_alter_post_nickname'),
    ]

    operations = [
    ]
