# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_merge_20250518_1314'),
        ('mainapp', '0012_vote'),
    ]

    operations = [
        # Merge migration - no operations needed
    ]