# Generated by Django 5.1.3 on 2025-05-27 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_merge_20250518_1314'),
        ('mainapp', '0012_vote'),
    ]

    operations = [
    ]
