# Generated by Django 5.1.3

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_scheduleplan_description'),
        ('mainapp', '0014_pinnedthread'),
    ]

    operations = [
        # Merge migration
    ]