# Generated by Django 5.1.3 on 2025-05-18 10:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blacklist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=511), blank=True, default=list, size=None, verbose_name='blacklist'),
        ),
    ]
