# Generated by Django 5.1.3 on 2025-05-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_blacklist'),
        ('accounts', '0002_userprofile'),
    ]

    operations = [
    ]
