# Generated by Django 5.1.3 on 2025-06-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_0002_user_blacklist_0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
