# Generated by Django 5.1.3 on 2025-06-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar_binary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_binary',
        ),
    ]
