# Generated by Django 5.1.3 on 2025-06-15 17:44

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_avatar_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.profile_picture_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='profile picture'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.profile_thumbnail_path, verbose_name='profile thumbnail'),
        ),
    ]
