# Generated by Django 5.1.3 on 2025-06-15 17:59

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_profile_picture_user_profile_picture_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_picture_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_thumbnail_path, verbose_name='profile thumbnail'),
        ),
    ]
